title       = "neurips"
baseURL     = "https://neurips-cli.tamnd.com/"
description = "A command line for NeurIPS papers."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/neurips-cli"
